Bump otel packages to resolve runtime pkg_resources err
We were getting an error like
ImportError: cannot import name 'Distribution' from
 'pkg_resources' (unknown location)
We hadn't updated our packages, so this breakage comes from
OpenTelemetry or its dependencies.  Deployed envs don't use metrics
yet, so we can safely bump this because we have it turned off.